version: "3.8"

services:
  jsinfo-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsinfo-indexer
    command: >
      sh -c "
      echo command_indexer &&
      echo scripts/startIndexerContainer.sh script will run here &&
      ulimit -c unlimited &&
      ls scripts/startIndexerContainer.sh || echo missing script &&
      IS_INDEXER_PROCESS=true sh scripts/startIndexerContainer.sh || true &&
      sleep 100000
      "
    environment:
      - JSINFO_INDEXER_SAVE_CACHE=1
      - JSINFO_INDEXER_READ_CACHE=1
      - JSINFO_INDEXER_N_WORKERS=2
      - JSINFO_INDEXER_BATCH_SIZE=250
      - JSINFO_INDEXER_POLL_MS=5000
      - JSINFO_INDEXER_REDDIS_CACHE=redis://:mypassword@jsinfo-redis:6379
      - JSINFO_INDEXER_LAVA_RPC=https://testnet2-rpc.lavapro.xyz:443/
      - JSINFO_INDEXER_START_BLOCK=2220430
      - JSINFO_INDEXER_RUN_MIGRATIONS=true
      - JSINFO_INDEXER_LAVA_REST_RPC_URL=https://lav1.rest.lava.build/
      - JSINFO_POSTGRESQL_URL=postgres://jsinfo:secret@jsinfo-postgres:5432/jsinfo
      - RELAYS_READ_POSTGRESQL_URL=postgres://jsinfo:secret@jsinfo-postgres:5432/relays
      - JSINFO_QUERY_PORT=8081
    depends_on:
      - jsinfo-redis
      - jsinfo-postgres

  jsinfo-query:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsinfo-query
    command: >
      sh -c "
      echo command_query_first_client &&
      echo scripts/startQueryContainer.sh script will run here &&
      ulimit -c unlimited &&
      ls scripts/startQueryContainer.sh || echo missing script &&
      scripts/startQueryContainer.sh || true &&
      sleep 100000
      "
    ports:
      - "8081:8081"
    environment:
      - JSINFO_QUERY_IS_DEBUG_MODE=true
      - JSINFO_QUERY_PORT=8081
      - JSINFO_QUERY_HOST=0.0.0.0
      - JSINFO_QUERY_FASITY_PRINT_LOGS=true
      - JSINFO_QUERY_REDDIS_CACHE=redis://:mypassword@jsinfo-redis:6379
      - JSINFO_POSTGRESQL_URL=postgres://jsinfo:secret@jsinfo-postgres:5432/jsinfo
      - RELAYS_READ_POSTGRESQL_URL=postgres://jsinfo:secret@jsinfo-postgres:5432/relays
    depends_on:
      - jsinfo-redis
      - jsinfo-postgres

  jsinfo-redis:
    image: redis/redis-stack:latest
    container_name: jsinfo-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass mypassword
    volumes:
      - jsinfo-redis-data:/data

  jsinfo-postgres:
    image: postgres:15
    container_name: jsinfo-postgres
    environment:
      - POSTGRES_USER=jsinfo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=jsinfo
    ports:
      - "5432:5432"
    volumes:
      - jsinfo-postgres-data:/var/lib/postgresql/data
      - ./docker-compose.init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  jsinfo-redis-data:
  jsinfo-postgres-data:
